# Generated by Django 5.1.15 on 2026-06-28 11:51

import apps.works.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('image', models.ImageField(upload_to='works/%Y/%m/', validators=[apps.works.validators.validate_work_image], verbose_name='فایل تصویر')),
                ('description', models.TextField(verbose_name='توضیحات و کپشن اثر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to=settings.AUTH_USER_MODEL, verbose_name='صاحب اثر')),
            ],
            options={
                'verbose_name': 'اثر عکاسی',
                'verbose_name_plural': 'آثار عکاسی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='works_work_user_id_2d7f18_idx')],
            },
        ),
    ]
