# Generated by Django 6.0.7 on 2026-07-09 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'اثر عکاسی', 'verbose_name_plural': 'آثار عکاسی'},
        ),
        migrations.RemoveIndex(
            model_name='work',
            name='works_work_user_id_2d7f18_idx',
        ),
        migrations.AddField(
            model_name='work',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='نام اصلی فایل'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['user', 'created_at', 'id'], name='works_work_user_id_6e548b_idx'),
        ),
    ]
