# Generated by Django 5.1.15 on 2026-06-28 11:38

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('job', models.CharField(max_length=150, verbose_name='شغل')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('national_code', models.CharField(max_length=10, unique=True, validators=[apps.core.validators.validate_national_code], verbose_name='کد ملی')),
                ('mobile', models.CharField(max_length=11, unique=True, validators=[apps.core.validators.validate_iranian_mobile], verbose_name='تلفن همراه')),
                ('province', models.CharField(max_length=100, verbose_name='استان محل سکونت')),
                ('city', models.CharField(max_length=100, verbose_name='شهر محل سکونت')),
                ('address', models.TextField(verbose_name='آدرس دقیق محل سکونت')),
                ('postal_code', models.CharField(max_length=10, validators=[apps.core.validators.validate_postal_code], verbose_name='کد پستی')),
                ('bale_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پیام\u200cرسان بله')),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پیام\u200cرسان تلگرام')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/', verbose_name='تصویر پروفایل')),
                ('is_mobile_verified', models.BooleanField(default=True, verbose_name='وضعیت تایید موبایل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='دسترسی کارمند')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'indexes': [models.Index(fields=['mobile'], name='accounts_us_mobile_646276_idx'), models.Index(fields=['national_code'], name='accounts_us_nationa_8afd66_idx')],
            },
        ),
    ]
